(function(){
'use strict';
const KEY='startupOS.sessions.v1',root=document.getElementById('studio');
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let pack,active='',info=null,globalError='',pending=new Map(),polls=new Map();
try{pack=JSON.parse(localStorage.getItem(KEY)||'null');if(!pack||!Array.isArray(pack.sessions))throw new Error('저장된 Venture Session이 없습니다.');active=new URLSearchParams(location.search).get('sessionId')||pack.activeId;if(!pack.sessions.some(x=>x._sessionId===active))active=pack.sessions[0]&&pack.sessions[0]._sessionId||'';}catch(e){globalError=e.message;pack={sessions:[]};}
const session=()=>pack.sessions.find(x=>x._sessionId===active),job=sid=>pending.get(sid);
function patch(sid,fn){const current=JSON.parse(localStorage.getItem(KEY)||'null');if(!current||!Array.isArray(current.sessions))throw new Error('세션 저장소가 사라졌습니다.');const p=current.sessions.find(x=>x._sessionId===sid);if(!p)throw new Error('원래 세션이 없습니다.');fn(p);p._updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(current));pack=current;return p;}
function log(sid,event,detail){patch(sid,p=>{p._events=[{at:new Date().toISOString(),type:event,message:detail},...(p._events||[])].slice(0,100);});}
function selectKind(p){
  var tech=(p.techStack||[]).map(x=>typeof x==="string"?x:[x.area,x.service,x.reason].filter(Boolean).join(" "));
  var flow=(p.serviceFlow||[]).map(x=>[x.title,x.user_action,x.system_action].filter(Boolean).join(" "));
  var text=[p.name,p.idea,p.problem,p.desiredOutcome].concat(p.mvpFeatures||[],tech,flow).filter(Boolean).join(" ");
  if(/영수증|receipt|ocr\s*가계부|품목.{0,12}ocr|ocr.{0,12}품목/i.test(text))return "receipt";
  if(/여행|travel|trip|packing|준비물|예약.{0,10}일정/i.test(text))return "travel";
  return "";
}
function money(value){return value==null?'미확정':'$'+Number(value).toFixed(6);}
function stateText(f){if(!f)return '아직 기능 Build 없음';if(f.verification&&f.verification.status==='INTEGRATION_VERIFIED')return '연동 검증 통과 · 폰 실사용 미검증';if(f.verification&&f.verification.status==='FAILED')return '검증 실패 · 배포 차단';return '구현됨 · 실제 검증 대기';}
function checks(rows){return (rows||[]).map(x=>'<div class="checkrow"><span>'+(x.status==='passed'?'✓':'✕')+'</span><div><strong>'+esc(x.id)+'</strong><div class="tiny">'+esc(x.message||x.evidence||x.status)+'</div>'+(x.responseId?'<div class="tiny">'+esc(x.model)+' · '+esc(x.responseId)+' · '+Math.round(x.latencyMs||0)+'ms</div>':'')+'</div></div>').join('');}
function trace(p){const d=p.functionalDiagnostics;if(!d)return '<div class="hint">실행 이력이 없습니다.</div>';return '<pre class="trace">'+esc(JSON.stringify(d,null,2))+'</pre>';}
function render(){
 const p=session();
 if(!p){root.innerHTML='<div class="pageTitle"><div><h1>Build</h1><div class="muted">Session not found</div></div></div><div class="errorbox">'+esc(globalError||'세션이 없습니다.')+'</div><a class="btn" href="/">← StartupOS</a>';return;}
 const f=p.functionalBuild,kind=selectKind(p),contract=info&&info.contracts[kind],busy=!!job(active),verified=!!(f&&f.verification&&f.verification.status==='INTEGRATION_VERIFIED'),deployment=f&&f.deployment,ready=!!(deployment&&deployment.readyState==='READY');
 const stageData=[['Contract',!!contract],['Build',!!f],['Verify',verified],['Deploy',ready],['Phone',false]];
 const inScope=contract?contract.acceptance:[];
 const outScope=contract?contract.exclusions:[];
 root.innerHTML=
 '<div class="studio-head"><a class="toplink" href="/">← StartupOS</a><select id="session">'+pack.sessions.map(s=>'<option value="'+esc(s._sessionId)+'" '+(s._sessionId===active?'selected':'')+'>'+esc(s.name)+' · '+esc(s._sessionId.slice(-7))+'</option>').join('')+'</select></div>'+
 '<div class="pageTitle"><div><h1>Build</h1><div class="muted">'+esc(p.name)+'</div></div><div class="metaRow"><span class="metaChip">'+esc(kind||'module unset')+'</span><span class="metaChip">'+esc(p._sessionId.slice(-8))+'</span><span class="metaChip">'+esc(stateText(f))+'</span></div></div>'+
 '<div class="stages">'+stageData.map(([text,pass],i)=>'<div class="stagebox '+(pass?'pass':'pending')+'"><strong>'+String(i+1)+'. '+text+'</strong>'+(pass?'Done':'Pending')+'</div>').join('')+'</div>'+
 (busy?'<section class="card"><div class="sectionHead"><h2>'+esc(job(active).label)+'</h2><span id="elapsed" class="tiny"></span></div><div class="busyline"></div><div class="muted">'+esc(job(active).message)+'</div></section>':'')+
 (p.functionalDiagnostics&&p.functionalDiagnostics.error?'<div class="errorbox" role="alert"><strong>'+esc(p.functionalDiagnostics.error)+'</strong><div class="tiny">'+esc(p.functionalDiagnostics.code||'')+' · HTTP '+esc(p.functionalDiagnostics.httpStatus||'-')+'</div></div>':'')+
 '<section class="card"><div class="sectionHead"><h2>Build scope</h2>'+(contract?'<span class="badge">'+esc(contract.title||kind)+'</span>':'')+'</div>'+
 (contract?'<div class="metaRow" style="margin-bottom:12px"><span class="metaChip">Session blueprint → '+esc(contract.title||kind)+'</span><span class="metaChip">Auto mapped</span></div><div class="two"><div><h3>In scope</h3><div class="scopeList">'+inScope.map(x=>'<div class="scopeItem">✓ '+esc(x)+'</div>').join('')+'</div><div><h3>Out scope</h3><div class="scopeList">'+outScope.map(x=>'<div class="scopeItem">— '+esc(x)+'</div>').join('')+'</div></div><label class="check"><input id="scope" type="checkbox" '+(p.functionalScopeApproved===kind?'checked':'')+' '+(busy?'disabled':'')+'>이 범위로 Build</label><button class="btn primary" id="assemble" '+(busy||p.functionalScopeApproved!==kind?'disabled':'')+'>'+(f?'New Build':'Build')+'</button>':'<div class="notice warn">현재 Session Blueprint와 연결된 Functional Capability가 아직 없습니다. Venture Lab에서 기능 범위를 먼저 확정하세요.</div>')+
 '</section>'+
 (f?'<section class="card"><div class="sectionHead"><h2>Build artifact</h2><span class="badge">IMPLEMENTED</span></div><div class="metaRow"><span class="metaChip">'+esc(f.bid)+'</span><span class="metaChip">'+esc(f.kind)+'</span><span class="metaChip">'+esc(f.createdAt)+'</span></div><div class="toolbar" style="margin-top:12px"><a class="btn primary" href="'+esc(f.previewUrl)+'" target="_blank" rel="noopener">Open app ↗</a><button class="btn" id="preview-toggle">Preview</button></div><div id="preview-area"></div><details><summary>Artifact checks</summary>'+checks(f.checks)+'</details></section>'+
 '<section class="card"><div class="sectionHead"><h2>Verify</h2><span class="badge">'+(verified?'VERIFIED':'PENDING')+'</span></div><button class="btn primary" id="verify" '+(busy?'disabled':'')+'>'+(verified?'Run again':'Run verification')+'</button>'+(f.verification?'<details '+(verified?'':'open')+'><summary>Verification evidence</summary>'+checks(f.verification.checks)+'</details>':'')+'</section>'+
 '<section class="card"><div class="sectionHead"><h2>Deploy</h2><span class="badge">'+(ready?'LIVE':deployment?esc(deployment.readyState||'DEPLOYING'):'PENDING')+'</span></div><div class="toolbar"><button class="btn primary" id="publish" '+(!verified||busy?'disabled':'')+'>Deploy verified build</button>'+(deployment?'<button class="btn" id="refresh-deploy">Refresh</button>':'')+(ready?'<a class="btn" target="_blank" rel="noopener" href="'+esc(deployment.url)+'">Open app ↗</a>':'')+'</div>'+(deployment&&deployment.url?'<div class="tiny" style="margin-top:10px">'+esc(deployment.url)+'</div>':'')+'</section>':'')+
 '<section class="card"><div class="sectionHead"><h2>Phone Test</h2><span class="badge">'+(p.functionalDeviceNote?'RECORDED':'PENDING')+'</span></div><label class="field"><span>Device / result / issue</span><textarea id="device-note" placeholder="Galaxy S23 / Chrome · camera, OCR, save OK">'+esc(p.functionalDeviceNote||'')+'</textarea></label><button class="btn" id="save-device">Save</button></section>'+
 '<details class="card"><summary>Diagnostics</summary>'+trace(p)+'<div class="tiny">'+esc((p.functionalBuildHistory||[]).length)+' previous builds · last cost '+money(p.functionalLastCost&&p.functionalLastCost.provider_usd)+'</div></details>';
 bind();
}

async function request(url,body,timeout=70000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const r=await fetch(url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,signal:controller.signal});const text=await r.text();let result;try{result=JSON.parse(text);}catch{throw Object.assign(new Error('서버가 JSON이 아닌 응답을 반환했습니다.'),{httpStatus:r.status});}if(!r.ok||!result.ok)throw Object.assign(new Error(result.error||'요청 실패'),{httpStatus:r.status,code:result.code});return result;}catch(e){if(e.name==='AbortError')throw new Error('요청 제한시간을 초과했습니다. 상태를 확인한 뒤 수동으로 재시도하세요.');throw e;}finally{clearTimeout(timer);}}
async function perform(sid,label,message,fn){if(pending.has(sid))return;const runId=crypto.randomUUID(),started=Date.now();pending.set(sid,{runId,started,label,message});patch(sid,p=>{p.functionalDiagnostics={runId,label,stage:'running',startedAt:new Date().toISOString()};});render();try{await fn(runId);patch(sid,p=>{if(p.functionalDiagnostics.runId===runId)p.functionalDiagnostics={...p.functionalDiagnostics,stage:'finished',elapsedMs:Date.now()-started,httpStatus:200};});}catch(e){patch(sid,p=>{if(p.functionalDiagnostics.runId===runId)p.functionalDiagnostics={...p.functionalDiagnostics,stage:'failed',error:e.message,code:e.code,httpStatus:e.httpStatus||null,elapsedMs:Date.now()-started};});}finally{pending.delete(sid);render();}}
function charge(p,cost,label,id){p.functionalLastCost=cost;if(cost&&cost.provider_usd!=null){p.costs||=[];if(!p.costs.some(row=>row[4]===id))p.costs.push([label,'OpenAI / live verification','Verification',cost.provider_usd,id]);}}
function bind(){document.getElementById('session').onchange=ev=>{active=ev.target.value;const url=new URL(location.href);url.searchParams.set('sessionId',active);history.replaceState(null,'',url);render();};const p=session(),sid=active;
 const scope=document.getElementById('scope');if(scope)scope.onchange=()=>{patch(sid,x=>{x.functionalScopeApproved=scope.checked?selectKind(x):null;});render();};
 const assemble=document.getElementById('assemble');if(assemble)assemble.onclick=()=>perform(sid,'기능 코드 조립','서버에서 기능 계약과 실행 파일을 검증합니다.',async()=>{const current=pack.sessions.find(x=>x._sessionId===sid),result=await request('/api/build',{action:'assemble',project:{_sessionId:sid,name:current.name},kind:selectKind(current),acceptedScope:current.functionalScopeApproved===selectKind(current)});patch(sid,x=>{if(x.functionalBuild)x.functionalBuildHistory=[x.functionalBuild,...(x.functionalBuildHistory||[])].slice(0,10);x.functionalBuild=result.build;x._phase='blueprint';});log(sid,'functional_implemented','기능 구현 완료. 실제 연동 검증 대기.');});
 const verify=document.getElementById('verify');if(verify)verify.onclick=()=>{const build=p.functionalBuild;perform(sid,'자동 기능 검증','브라우저 회귀 증거와 실제 API 응답을 확인합니다.',async()=>{const result=await request('/api/build',{action:'verify',descriptor:build.descriptor||build,sessionId:sid,liveConsent:true});patch(sid,x=>{if(x.functionalBuild.bid!==build.bid)throw new Error('새 Build가 생성되어 이전 응답을 적용하지 않았습니다.');x.functionalBuild.verification=result.verification;x._phase=result.verification.status==='INTEGRATION_VERIFIED'?'build':'blueprint';charge(x,result.cost,'Build live verification',build.bid+':'+result.verification.checkedAt);});log(sid,'functional_verified',result.verification.status);});};
 const preview=document.getElementById('preview-toggle');if(preview)preview.onclick=()=>{const area=document.getElementById('preview-area');if(area.firstChild){area.replaceChildren();return;}const frame=document.createElement('iframe');frame.className='preview-frame';frame.allow='camera';frame.title='실제 기능 앱 미리보기';frame.src=p.functionalBuild.previewUrl;area.appendChild(frame);};
 const publish=document.getElementById('publish');if(publish)publish.onclick=()=>{const build=p.functionalBuild;perform(sid,'테스트 배포 요청','서버가 현재 소스로 다시 조립하고 실제 검증을 재실행한 뒤 배포합니다.',async()=>{const result=await request('/api/publish',{sessionId:sid,approved:true,liveConsent:true,descriptor:build.descriptor||build});patch(sid,x=>{if(x.functionalBuild.bid!==build.bid)throw new Error('다른 Build로 전환되었습니다.');x.functionalBuild.verification=result.verification;x.functionalBuild.deployment=result.deployment;charge(x,result.cost,'Publish re-verification',build.bid+':publish:'+new Date().toISOString());});log(sid,'deployment_requested',result.deployment.id);pollDeployment(sid,build.bid);});};
 const refresh=document.getElementById('refresh-deploy');if(refresh)refresh.onclick=()=>pollDeployment(sid,p.functionalBuild.bid);
 const save=document.getElementById('save-device');if(save)save.onclick=()=>{const note=document.getElementById('device-note').value;patch(sid,x=>{x.functionalDeviceNote=note;x.functionalDeviceEvidence={source:'user_report',at:new Date().toISOString(),note,buildId:x.functionalBuild&&x.functionalBuild.bid};});log(sid,'phone_user_report','실기기 사용자 확인 기록 저장');render();};
}
async function pollDeployment(sid,bid){if(polls.has(sid))return;polls.set(sid,true);try{for(let i=0;i<20;i++){const p=pack.sessions.find(x=>x._sessionId===sid),d=p&&p.functionalBuild&&p.functionalBuild.bid===bid&&p.functionalBuild.deployment;if(!d||!d.id)break;const result=await request('/api/publish?id='+encodeURIComponent(d.id));patch(sid,x=>{if(x.functionalBuild.bid!==bid)return;x.functionalBuild.deployment={...d,...result.deployment};if(result.deployment.readyState==='READY')x._phase='deploy';});render();if(['READY','ERROR','CANCELED'].includes(result.deployment.readyState))break;await new Promise(r=>setTimeout(r,3000));}}catch(e){patch(sid,x=>{x.functionalDiagnostics={label:'Deployment status',error:e.message,code:e.code,httpStatus:e.httpStatus,stage:'failed'};});render();}finally{polls.delete(sid);}}
setInterval(()=>{const el=document.getElementById('elapsed'),j=job(active);if(el&&j)el.textContent=Math.floor((Date.now()-j.started)/1000)+'초';},1000);
window.addEventListener('storage',ev=>{if(ev.key===KEY){try{pack=JSON.parse(ev.newValue);if(!pending.size)render();}catch{}}});
render();request('/api/build').then(data=>{info=data;render();}).catch(e=>{globalError=e.message;render();});
})();
