(function(){
'use strict';
const C=window.APP_CONFIG,D=window.VentureData,root=document.getElementById('app');
const escape=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID();
const amount=(n,c='KRW')=>new Intl.NumberFormat('ko-KR',{style:'currency',currency:/^[A-Z]{3}$/.test(c)?c:'KRW',maximumFractionDigits:c==='KRW'?0:2}).format(Number(n||0));
let store,records=[],storageError='';
try{store=D.storage(localStorage,C.sessionId,'receipt');records=store.read();}catch(e){storageError='브라우저 저장소를 열 수 없습니다. 새 창으로 앱을 열어주세요. '+e.message;}
let view='home',draft=null,image=null,imageUrl='',stream=null,busy=false,error='',status='',elapsed=0,timer=null,controller=null,sequence=0,lastOcr=null;
let month=new Date().toISOString().slice(0,7),consent=false;
function emit(type,detail={}){const entry={type,at:new Date().toISOString(),sessionId:C.sessionId,buildId:C.buildId,...detail};try{const key='startup-os:observations:'+C.sessionId;const old=JSON.parse(localStorage.getItem(key)||'[]');localStorage.setItem(key,JSON.stringify([entry,...old].slice(0,50)));}catch{}if(window.parent!==window)window.parent.postMessage({type:'startup-os-evidence',entry},location.origin);}
function stopCamera(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;}
function releaseImage(){if(imageUrl)URL.revokeObjectURL(imageUrl);imageUrl='';image=null;}
function nav(){return '<nav class="tabs"><div>'+[['home','홈'],['scan','영수증 촬영'],['records','기록'],['summary','소비 요약']].map(([id,label])=>'<button data-nav="'+id+'" class="'+(view===id?'active':'')+'">'+label+'</button>').join('')+'</div></nav>';}
function header(){return '<header class="header"><div><div class="eyebrow">RECEIPT / '+escape(C.buildId.slice(-6))+'</div><h1>'+escape(C.name)+'</h1><div class="muted">사진에서 품목까지. 확인하고 저장하세요.</div></div><span class="badge">'+(lastOcr?'최근 OCR 성공':'OCR 실호출 가능')+'</span></header>';}
function home(){const s=D.summary(records,month);return '<section class="card hero"><div class="muted">이번 달 영수증 지출 · '+escape(month)+'</div><div class="big">'+(Object.entries(s.totals).map(([c,n])=>amount(n,c)).join(' / ')||'0원')+'</div><div class="muted">'+records.filter(r=>r.purchase_date.startsWith(month)).length+'건 저장</div><button class="btn light full" data-action="new" style="margin-top:18px">영수증 촬영하기</button></section><div class="grid"><button class="btn" data-action="album-home">앨범에서 가져오기</button><button class="btn" data-action="manual">직접 입력</button></div><div class="notice">OCR은 사진을 OpenAI API에 전송한 후 실행됩니다. 전송 전에 동의를 받으며, 이 앱은 사진 원본을 저장하지 않습니다. 저장된 거래는 이 기기에만 남습니다.</div><section class="card"><div class="row between"><h2>최근 영수증</h2><button class="btn" data-nav="records">전체</button></div>'+listRecords(records.slice(-3).reverse())+'</section>';}
function listRecords(list){return list.length?list.map(r=>'<article class="record"><div class="row between"><div><strong>'+escape(r.merchant)+'</strong><div class="hint">'+escape(r.purchase_date)+' · '+r.items.length+'개 품목'+(r.source==='manual'?' · 직접 입력':' · OCR')+'</div></div><div class="amount">'+amount(r.total_amount,r.currency)+'</div></div><p class="muted">'+r.items.slice(0,4).map(x=>escape(x.name)).join(' · ')+'</p><div class="row"><button class="btn" data-edit="'+r.id+'">확인 / 수정</button><button class="btn danger" data-delete="'+r.id+'">삭제</button></div></article>').join(''):'<div class="empty">저장한 영수증이 없습니다.<br>촬영 후 인식 결과를 확인해 보세요.</div>';}
function controls(){return '<input id="camera-file" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" hidden><input id="album-file" type="file" accept="image/jpeg,image/png,image/webp" hidden><section class="card"><div class="step">01 / 촬영 또는 사진 선택</div><div class="grid"><button class="btn primary" data-action="camera" '+(busy?'disabled':'')+'>카메라 열기</button><button class="btn" data-action="album" '+(busy?'disabled':'')+'>앨범 선택</button></div>'+(stream?'<video id="camera-video" class="camera" autoplay muted playsinline style="margin-top:14px"></video><div class="row" style="margin-top:10px"><button class="btn primary" data-action="capture">촬영</button><button class="btn" data-action="close-camera">카메라 닫기</button></div>':'')+(imageUrl?'<img class="photo" alt="선택한 영수증 미리보기" src="'+imageUrl+'" style="margin-top:14px"><label class="check"><input id="consent" type="checkbox" '+(consent?'checked':'')+' '+(busy?'disabled':'')+'>이 사진을 OpenAI API로 전송하여 OCR 분석하는 데 동의합니다.</label><button class="btn primary full" data-action="ocr" '+(busy||!consent?'disabled':'')+'>'+(busy?'분석 중…':'사진 분석하기')+'</button>':'')+(busy?'<div class="busyline"></div><div class="row between"><span role="status" class="muted">실제 OCR 요청 진행 중</span><span id="elapsed" class="tiny">'+elapsed+'초</span><button class="btn" data-action="cancel">중지</button></div>':'')+(status?'<div class="notice" role="status">'+escape(status)+'</div>':'')+'</section>';}
function editForm(){if(!draft)return '';const r=draft;return '<section class="card"><div class="step">02 / 인식 결과 확인 및 수정</div><form id="receipt-form"><div class="grid"><label class="field"><span>상호</span><input data-field="merchant" value="'+escape(r.merchant)+'" required></label><label class="field"><span>구매일</span><input data-field="purchase_date" type="date" value="'+escape(r.purchase_date)+'" required></label><label class="field"><span>총액</span><input data-field="total_amount" type="number" min="0" step="0.01" value="'+escape(r.total_amount)+'" required></label><label class="field"><span>통화</span><select data-field="currency">'+['KRW','USD','EUR','JPY','THB'].map(x=>'<option '+(x===r.currency?'selected':'')+'>'+x+'</option>').join('')+'</select></label></div><h3>품목</h3><div class="hint">읽지 못한 숫자는 공란입니다. 저장 전 직접 확인하세요.</div>'+r.items.map((item,i)=>'<div class="item" data-line="'+i+'"><div class="item-grid"><input aria-label="품목명 '+(i+1)+'" data-item="'+i+'" data-key="name" value="'+escape(item.name)+'" required><input aria-label="수량 '+(i+1)+'" data-item="'+i+'" data-key="quantity" type="number" min="0.001" step="0.001" value="'+escape(item.quantity)+'" required><input aria-label="품목 금액 '+(i+1)+'" data-item="'+i+'" data-key="line_total" type="number" min="0" step="0.01" value="'+escape(item.line_total)+'" required></div><div class="item-meta"><select aria-label="카테고리 '+(i+1)+'" data-item="'+i+'" data-key="category">'+['식료품','외식','생활용품','육아','교통','의료','기타'].map(c=>'<option '+(c===item.category?'selected':'')+'>'+c+'</option>').join('')+'</select><button type="button" class="btn danger" data-remove-item="'+i+'">품목 삭제</button></div></div>').join('')+'<button class="btn full" type="button" data-action="add-item">+ 품목 추가</button><div id="reconcile"></div><label class="check"><input data-field="differenceAcknowledged" type="checkbox" '+(r.differenceAcknowledged?'checked':'')+'>할인·세금·오인식 등 총액 차이를 확인했습니다.</label>'+(r.warnings&&r.warnings.length?'<div class="notice warn">'+r.warnings.map(escape).join('<br>')+'</div>':'')+'<label class="field"><span>메모</span><textarea data-field="note">'+escape(r.note||'')+'</textarea></label><button class="btn primary full" '+(busy||storageError?'disabled':'')+'>확인한 영수증 저장</button><p class="hint">인식 결과는 검토 전까지 저장되지 않습니다.</p></form></section>';}
function summary(){const s=D.summary(records,month);return '<section class="card"><h2>월별 소비</h2><label class="field"><span>월 선택</span><input id="month" type="month" value="'+month+'"></label>'+Object.entries(s.totals).map(([c,n])=>'<h3>'+amount(n,c)+'</h3>'+Object.entries(s.categories[c]||{}).sort((a,b)=>b[1]-a[1]).map(([k,v])=>'<div class="record row between"><strong>'+escape(k)+'</strong><span>'+amount(v,c)+'</span></div>').join('')).join('')+(Object.keys(s.totals).length?'':'<div class="empty">선택한 월의 기록이 없습니다.</div>')+'<p class="hint">카테고리 합계는 품목 금액 기준입니다. 세금·할인 등의 차이로 총 지출과 다를 수 있습니다.</p></section><button class="btn full" data-action="export">내 기록 JSON 백업</button>';}
function render(){root.className='app';root.innerHTML=header()+(storageError?'<div class="errorbox">'+escape(storageError)+'</div>':'')+(error?'<div class="errorbox" role="alert">'+escape(error)+'</div>':'')+(view==='home'?home():view==='scan'?controls()+editForm():view==='records'?'<section class="card"><h2>영수증 기록</h2>'+listRecords(records.slice().reverse())+'</section>':summary())+nav();bind();updateTotals();if(stream){const video=document.getElementById('camera-video');if(video){video.srcObject=stream;video.play().catch(()=>{});}}}
function updateTotals(){const el=document.getElementById('reconcile');if(!el||!draft)return;const r=D.reconcile(draft);el.className='notice '+(r.requiresReview?'warn':'');el.textContent='품목 합계 '+amount(r.sum,draft.currency)+' · 총액 차이 '+(r.difference==null?'확인 필요':amount(r.difference,draft.currency));}
function newDraft(){return {id:uid(),merchant:'',purchase_date:'',currency:'KRW',total_amount:null,items:[{name:'',quantity:1,unit_price:null,line_total:null,category:'기타'}],warnings:[],differenceAcknowledged:false,source:'manual'};}
async function select(file){if(busy||!file)return;stopCamera();releaseImage();draft=null;status='';error='';consent=false;if(!/^image\/(jpeg|png|webp)$/.test(file.type)){error='JPEG / PNG / WebP 파일을 선택하세요. HEIC 사진은 기기에서 JPEG로 변환해 주세요.';render();return;}if(file.size>20000000){error='20MB 이하 사진을 선택하세요.';render();return;}image=file;imageUrl=URL.createObjectURL(file);emit('image_selected');render();}
async function camera(){error='';if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){document.getElementById('camera-file').click();return;}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920}},audio:false});emit('camera_opened');render();}catch(e){error='카메라 권한이 거부되었거나 사용할 수 없습니다. 아래 앨범 선택 또는 기기 촬영으로 진행하세요.';render();const input=document.getElementById('camera-file');if(input)input.hidden=false;}}
async function capture(){const video=document.getElementById('camera-video');if(!video||!video.videoWidth)return;const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);canvas.toBlob(blob=>{if(blob){emit('camera_captured');select(new File([blob],'receipt.jpg',{type:'image/jpeg'}));}},'image/jpeg',0.9);}
async function prepare(file){const url=URL.createObjectURL(file);try{const img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('사진을 읽을 수 없습니다.'));i.src=url;});const scale=Math.min(1,2200/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);let imageData=canvas.toDataURL('image/jpeg',.85);if(imageData.length>3400000)imageData=canvas.toDataURL('image/jpeg',.65);if(imageData.length>3400000)throw new Error('사진이 너무 큽니다. 영수증 영역만 잘라 다시 선택하세요.');return imageData;}finally{URL.revokeObjectURL(url);}}
async function analyze(){if(!image||!consent||busy)return;const attempt=++sequence;busy=true;error='';status='';draft=null;elapsed=0;render();const started=Date.now();timer=setInterval(()=>{elapsed=Math.floor((Date.now()-started)/1000);const el=document.getElementById('elapsed');if(el)el.textContent=elapsed+'초';},500);controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),55000);try{const data=await prepare(image);const r=await fetch(C.ocrEndpoint||'/api/receipt-ocr',{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json','X-StartupOS-App':C.appToken},body:JSON.stringify({image:data,consent:true,sessionId:C.sessionId})});const raw=await r.text();let payload;try{payload=JSON.parse(raw);}catch{throw new Error('서버가 JSON이 아닌 응답을 반환했습니다. HTTP '+r.status);}if(!r.ok||!payload.ok)throw new Error(payload.error||'OCR 요청 실패');if(attempt!==sequence)return;if(records.some(x=>x.imageDigest===payload.image_digest))throw new Error('이미 저장한 영수증입니다. 기록에서 수정하세요.');draft={...payload.result,id:uid(),source:'ocr',imageDigest:payload.image_digest,providerResponseId:payload.response_id,differenceAcknowledged:false,note:''};lastOcr={model:payload.model,responseId:payload.response_id,cost:payload.cost};status='OCR 응답 수신 · '+draft.items.length+'개 품목 · '+(payload.latency_ms/1000).toFixed(1)+'초. 읽지 못한 값과 경고를 확인하세요.';emit('live_ocr_succeeded',{responseId:payload.response_id,model:payload.model,usage:payload.usage,cost:payload.cost});}catch(e){if(attempt===sequence)error=e.name==='AbortError'?'분석을 중지했거나 요청 제한시간을 초과했습니다. 선택한 사진으로 다시 시도할 수 있습니다.':e.message;}finally{clearTimeout(timeout);clearInterval(timer);if(attempt===sequence){busy=false;controller=null;render();}}}
function saveDraft(){try{const next=D.receiptSave(records,{...draft,updatedAt:new Date().toISOString()});if(!store)throw new Error('저장소를 사용할 수 없습니다.');store.write(next);records=next;emit('receipt_saved',{recordId:draft.id});draft=null;releaseImage();view='records';error='';status='';render();}catch(e){error=e.message;render();}}
function bind(){root.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{if(busy)return;stopCamera();view=b.dataset.nav;error='';render();});root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='new'){if(busy)return;draft=null;releaseImage();error='';status='';view='scan';render();}if(a==='album-home'){view='scan';render();document.getElementById('album-file').click();}if(a==='manual'){draft=newDraft();view='scan';render();}if(a==='album')document.getElementById('album-file').click();if(a==='camera')camera();if(a==='capture')capture();if(a==='close-camera'){stopCamera();render();}if(a==='ocr')analyze();if(a==='cancel'&&controller)controller.abort();if(a==='add-item'){draft.items.push({name:'',quantity:1,unit_price:null,line_total:null,category:'기타'});render();}if(a==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(records,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='receipts-'+C.sessionId+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
for(const id of ['camera-file','album-file']){const input=document.getElementById(id);if(input)input.onchange=()=>select(input.files&&input.files[0]);}
const cb=document.getElementById('consent');if(cb)cb.onchange=()=>{consent=cb.checked;const btn=root.querySelector('[data-action=ocr]');if(btn)btn.disabled=!consent||busy;};
root.querySelectorAll('[data-field]').forEach(el=>el.oninput=()=>{const k=el.dataset.field;draft[k]=el.type==='checkbox'?el.checked:k==='total_amount'?D.number(el.value):el.value;updateTotals();});
root.querySelectorAll('[data-item]').forEach(el=>el.oninput=()=>{const k=el.dataset.key;draft.items[Number(el.dataset.item)][k]=['quantity','line_total'].includes(k)?D.number(el.value):el.value;updateTotals();});
root.querySelectorAll('[data-remove-item]').forEach(b=>b.onclick=()=>{draft.items.splice(Number(b.dataset.removeItem),1);render();});
root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{draft=JSON.parse(JSON.stringify(records.find(r=>r.id===b.dataset.edit)));releaseImage();view='scan';error='';render();});
root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(!confirm('이 영수증을 삭제할까요?'))return;try{const next=records.filter(r=>r.id!==b.dataset.delete);store.write(next);records=next;emit('receipt_deleted');render();}catch(e){error=e.message;render();}});
const form=document.getElementById('receipt-form');if(form)form.onsubmit=e=>{e.preventDefault();if(!busy)saveDraft();};const filter=document.getElementById('month');if(filter)filter.onchange=()=>{month=filter.value;render();};}
window.addEventListener('pagehide',()=>{stopCamera();if(controller)controller.abort();});
if(matchMedia('(display-mode: standalone)').matches)emit('standalone_launched');
if(!C.preview&&'serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(e=>{error='오프라인 캐시 설치 실패: '+e.message;render();});
render();emit('app_opened');
})();
