(function(){
'use strict';
const C=window.APP_CONFIG,D=window.VentureData,root=document.getElementById('app');
const e=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let store,trips=[],error='',selected='',filter='all',editTrip=null,editItem=null;
try{store=D.storage(localStorage,C.sessionId,'travel');trips=store.read();selected=trips[0]&&trips[0].id||'';}catch(x){error='저장소 오류: '+x.message;}
const uid=()=>crypto.randomUUID(),trip=()=>trips.find(x=>x.id===selected);
function persist(next){store.write(next);trips=next;}
function event(type){try{const key='startup-os:observations:'+C.sessionId,old=JSON.parse(localStorage.getItem(key)||'[]');localStorage.setItem(key,JSON.stringify([{type,at:new Date().toISOString(),buildId:C.buildId,sessionId:C.sessionId},...old].slice(0,50)));}catch{}}
function header(){return '<header class="header"><div><div class="eyebrow">TRIP / '+e(C.buildId.slice(-6))+'</div><h1>'+e(C.name)+'</h1><div class="muted">준비부터 출발까지, 잊지 않도록.</div></div><button class="btn" data-action="new-trip">+ 여행</button></header>';}
function tripForm(){if(!editTrip)return '';return '<section class="card"><h2>여행 정보</h2><form id="trip-form"><label class="field"><span>여행지</span><input name="destination" value="'+e(editTrip.destination)+'" required></label><div class="grid"><label class="field"><span>출발일</span><input name="start" type="date" value="'+e(editTrip.start)+'" required></label><label class="field"><span>귀국일</span><input name="end" type="date" value="'+e(editTrip.end)+'" required></label></div><label class="field"><span>여행 메모</span><textarea name="note">'+e(editTrip.note||'')+'</textarea></label><div class="row"><button class="btn primary">여행 저장</button><button class="btn" type="button" data-action="cancel-trip">취소</button></div></form></section>';}
function itemForm(){if(!editItem)return '';return '<section class="card"><h2>할 일 / 준비물 / 예약</h2><form id="item-form"><label class="field"><span>분류</span><select name="kind">'+[['task','할 일'],['packing','준비물'],['reservation','예약']].map(([id,label])=>'<option value="'+id+'" '+(editItem.kind===id?'selected':'')+'>'+label+'</option>').join('')+'</select></label><label class="field"><span>제목</span><input name="title" value="'+e(editItem.title)+'" required></label><label class="field"><span>기한 / 예약일</span><input name="due" type="date" value="'+e(editItem.due||'')+'"></label><label class="field"><span>예약 링크 (선택)</span><input name="url" type="url" value="'+e(editItem.url||'')+'" placeholder="https://"></label><label class="field"><span>메모</span><textarea name="note">'+e(editItem.note||'')+'</textarea></label><div class="row"><button class="btn primary">항목 저장</button><button class="btn" type="button" data-action="cancel-item">취소</button></div></form></section>';}
function list(t){const items=t.items.filter(x=>filter==='all'||filter==='open'&&!x.done||x.kind===filter).slice().sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'));return '<section class="card"><div class="row between"><h2>여행 준비</h2><button class="btn primary" data-action="new-item">+ 항목</button></div><select id="filter">'+[['all','전체'],['open','미완료'],['task','할 일'],['packing','준비물'],['reservation','예약']].map(([id,label])=>'<option value="'+id+'" '+(filter===id?'selected':'')+'>'+label+'</option>').join('')+'</select>'+items.map(x=>'<article class="task '+(x.done?'done':'')+'"><input type="checkbox" aria-label="'+e(x.title)+' 완료" data-toggle="'+x.id+'" '+(x.done?'checked':'')+'><div class="grow"><strong class="task-title">'+e(x.title)+'</strong><div class="hint">'+e({task:'할 일',packing:'준비물',reservation:'예약'}[x.kind])+' · '+e(x.due||'날짜 없음')+'</div>'+(x.note?'<p class="muted">'+e(x.note)+'</p>':'')+(D.safeLink(x.url)?'<a href="'+e(D.safeLink(x.url))+'" target="_blank" rel="noopener noreferrer">예약 링크 열기 ↗</a>':'')+'<div class="row" style="margin-top:8px"><button class="btn" data-edit-item="'+x.id+'">수정</button><button class="btn danger" data-delete-item="'+x.id+'">삭제</button></div></div></article>').join('')+(items.length?'':'<div class="empty">여행 준비 항목을 추가하세요.<br>할 일과 준비물을 날짜별로 관리합니다.</div>')+'</section>';}
function render(){const t=trip(),p=t?D.progress(t.items):null;root.className='app';root.innerHTML=header()+(error?'<div class="errorbox" role="alert">'+e(error)+'</div>':'')+(trips.length?'<select id="trip-select" aria-label="여행 선택">'+trips.map(x=>'<option value="'+x.id+'" '+(selected===x.id?'selected':'')+'>'+e(x.destination)+' · '+e(x.start)+'</option>').join('')+'</select>':'')+tripForm()+(t?'<section class="card hero"><div class="row between"><div class="eyebrow" style="color:#c6e8dc">'+e(t.start)+' — '+e(t.end)+'</div><span class="badge" style="color:#155e59">'+(D.daysUntil(t.start)>=0?'D-'+D.daysUntil(t.start):'여행 시작 후 '+Math.abs(D.daysUntil(t.start))+'일')+'</span></div><h1>'+e(t.destination)+'</h1><p class="muted">'+e(t.note||'여행 준비를 차근차근 완료해 보세요.')+'</p><div class="row between"><strong>'+p.done+' / '+p.total+' 완료</strong><span>'+p.percent+'%</span></div><div class="meter"><i style="width:'+p.percent+'%;background:#92dac3"></i></div><div class="row"><button class="btn light" data-action="edit-trip">여행 수정</button><button class="btn light" data-action="seed">기본 준비물 추가</button></div></section>'+itemForm()+list(t)+'<div class="row"><button class="btn" data-action="export">여행 데이터 백업</button><button class="btn danger" data-action="delete-trip">여행 삭제</button></div>':editTrip?'':'<section class="card empty">아직 여행이 없습니다.<br><button class="btn primary" data-action="new-trip">첫 여행 만들기</button></section>')+'<p class="hint">이 기기에만 저장됩니다. 알림 / 예약 API / 가족 동기화는 이 버전의 구현 범위에 포함되지 않습니다.</p>';bind();}
function attempt(fn){try{fn();error='';render();}catch(x){error=x.message;render();}}
function bind(){root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action,t=trip();if(a==='new-trip'){editTrip={id:uid(),destination:'',start:'',end:'',note:'',items:[]};render();}if(a==='cancel-trip'){editTrip=null;render();}if(a==='edit-trip'&&t){editTrip=JSON.parse(JSON.stringify(t));render();}if(a==='new-item'&&t){editItem={id:uid(),kind:'task',title:'',due:'',note:'',url:'',done:false};render();}if(a==='cancel-item'){editItem=null;render();}if(a==='seed'&&t)attempt(()=>{const titles=['신분증 / 여권 확인','충전기 챙기기','숙소 예약 확인'];const next=JSON.parse(JSON.stringify(trips)),n=next.find(x=>x.id===selected);for(const title of titles)if(!n.items.some(x=>x.title===title))n.items.push({id:uid(),kind:'packing',title,due:t.start,url:'',note:'',done:false});persist(next);});if(a==='delete-trip'&&t&&confirm('여행과 모든 준비 항목을 삭제할까요?'))attempt(()=>{persist(trips.filter(x=>x.id!==selected));selected=trips[0]&&trips[0].id||'';editTrip=null;editItem=null;});if(a==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(trips,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='trips-'+C.sessionId+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
const select=document.getElementById('trip-select');if(select)select.onchange=()=>{selected=select.value;editTrip=null;editItem=null;render();};const f=document.getElementById('filter');if(f)f.onchange=()=>{filter=f.value;render();};
const form=document.getElementById('trip-form');if(form)form.onsubmit=ev=>{ev.preventDefault();const data=Object.fromEntries(new FormData(form));attempt(()=>{const t=D.validateTrip({...editTrip,...data});const next=trips.filter(x=>x.id!==t.id);next.push(t);persist(next);selected=t.id;editTrip=null;event('trip_saved');});};
const itemFormEl=document.getElementById('item-form');if(itemFormEl)itemFormEl.onsubmit=ev=>{ev.preventDefault();const data=Object.fromEntries(new FormData(itemFormEl));attempt(()=>{if(!data.title.trim())throw new Error('제목을 입력하세요.');if(data.due&&!D.dateValid(data.due))throw new Error('기한을 확인하세요.');if(data.url&&!D.safeLink(data.url))throw new Error('http / https 예약 링크만 허용됩니다.');const next=JSON.parse(JSON.stringify(trips)),t=next.find(x=>x.id===selected);t.items=t.items.filter(x=>x.id!==editItem.id);t.items.push({...editItem,...data});persist(next);editItem=null;event('trip_item_saved');});};
root.querySelectorAll('[data-toggle]').forEach(cb=>cb.onchange=()=>attempt(()=>{const next=JSON.parse(JSON.stringify(trips)),item=next.find(x=>x.id===selected).items.find(x=>x.id===cb.dataset.toggle);item.done=cb.checked;persist(next);event('trip_item_toggled');}));
root.querySelectorAll('[data-edit-item]').forEach(b=>b.onclick=()=>{editItem=JSON.parse(JSON.stringify(trip().items.find(x=>x.id===b.dataset.editItem)));render();});
root.querySelectorAll('[data-delete-item]').forEach(b=>b.onclick=()=>attempt(()=>{const next=JSON.parse(JSON.stringify(trips)),t=next.find(x=>x.id===selected);t.items=t.items.filter(x=>x.id!==b.dataset.deleteItem);persist(next);}));}
if(!C.preview&&'serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(x=>{error='오프라인 설치 실패: '+x.message;render();});
if(matchMedia('(display-mode: standalone)').matches)event('standalone_launched');render();event('app_opened');
})();
